name: islamic
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  youtube_player_flutter:
  dots_indicator:
  flutter_svg:
  build_runner:
  dartz:
  shared_preferences:
  get_it:
  easy_localization:
  flutter_phoenix:
  flutter_bloc:
  equatable:
  flutter_screenutil:
  conditional_builder_null_safety:
  json_serializable:
  json_annotation:
  floor:
  floor_generator:
  retrofit:
  retrofit_generator:
  dio:
  pretty_dio_logger:
  internet_connection_checker:
  location:
  geocoding:
  wakelock:
  url_launcher:
  intl:
  google_fonts:
  sqflite:





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/quran/
    - assets/json/
    - assets/translations/
    - assets/images/pillars/


  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
    - family: UthmanTN
      fonts:
        - asset: assets/fonts/UthmanTNB.ttf
          weight: 700
        - asset: assets/fonts/UthmanTN.ttf
          weight: 400
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/Hafs.ttf
